import { Provider } from "@/components/ui/provider";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["cyrillic"],
});

export const metadata = {
  title: "Gates Of Egypt",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body className={montserrat.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
